[package]
name = "frontend_rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "vale_backend"

[package.metadata.rust-analyzer]
rustc_private = true

[features]
# Enables rust interop. Take this out to get a standalone Valen compiler.
rust_interop = []

horizon = ["rust_interop"]

borrow_checker_experimental = []

# Runs all tests without the C++ backend. Delete this soon.
no_backend = []

[build-dependencies]
cmake = "0.1"

[dependencies]
bumpalo = { version = "3", features = ["collections", "allocator-api2"] }
indexmap = "2"
hashbrown = "0.16"
rustc-hash = "2"
paste = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[dev-dependencies]
tempfile = "3"

[lib]
name = "frontend_rust"
path = "src/lib.rs"

[[bin]]
name = "valec"
path = "src/bin/valec/main.rs"

[[bin]]
name = "valenc-rs"
path = "src/typing/rust_interop/driver/main.rs"
required-features = ["rust_interop"]

[[bin]]
name = "valen"
path = "src/typing/rust_interop/valen/main.rs"
required-features = ["rust_interop"]

[profile.profiling]
inherits = "release"
debug = true
