use std::{fs, io};
use std::path::{Path, PathBuf};

// Returns the -->'d path in the below dir structure:
//   testvalenproj/
//     src/bin.rs                          (not actually generated by tests, but here in spirit)
//     target/
//       debug/
// -->     deps/
//           valenc-stubs/
//             testvalenproj/
//               bin.rs                    (input for the instantiating pass)
//           libsimple_dep_rust_lib.rlib   (rustc-compiled rlib from simple_dep_rust_lib)
pub fn deps_dir_of(temp_dir: &Path) -> PathBuf {
  temp_dir
      .join("target")
      .join("debug")
      .join("deps")
}

// Returns the -->'d path in the below dir structure:
//   testvalenproj/
//     src/bin.rs                          (not actually generated by tests, but here in spirit)
//     target/
//       debug/
//         deps/
//           valenc-stubs/
// -->         testvalenproj/
//               bin.rs                    (input for the instantiating pass)
//           libsimple_dep_rust_lib.rlib   (rustc-compiled rlib from simple_dep_rust_lib)
//   simple_dep_rust_lib/                  (dir for a rust crate, copied from fixtures)
//     src/lib.rs
pub fn stubs_dir_of(valen_project_dir: &Path) -> PathBuf {
  stubs_dir_in(&deps_dir_of(valen_project_dir), "stub")
}

// Returns the -->'d path in the below dir structure:
//   testvalenproj/
//     src/bin.rs                          (not actually generated by tests, but here in spirit)
//     target/
//       debug/
//         deps/
//           valenc-stubs/
//             testvalenproj/
// -->           bin.rs                    (input for the instantiating pass)
//           libsimple_dep_rust_lib.rlib   (rustc-compiled rlib from simple_dep_rust_lib)
//   simple_dep_rust_lib/                  (dir for a rust crate, copied from fixtures)
//     src/lib.rs
pub fn importer_file_path(valen_project_dir: &Path) -> PathBuf {
  importer_file_path_in(&deps_dir_of(valen_project_dir), "stub")
}

pub fn stubs_dir_in(out_dir: &Path, crate_name: &str) -> PathBuf {
  out_dir
      .parent()
      .expect("rustc --out-dir has no parent directory")
      .join("valenc-stubs")
      .join(crate_name)
}

pub fn importer_file_path_in(out_dir: &Path, crate_name: &str) -> PathBuf {
  stubs_dir_in(out_dir, crate_name).join("lib.rs")
}

pub fn final_file_path_in(out_dir: &Path, crate_name: &str, crate_type: &str) -> PathBuf {
  let file_name = match crate_type {
    "bin" => "bin.rs",
    "lib" | "rlib" => "lib.rs",
    other => panic!("unsupported --crate-type for a Valen crate: {other}"),
  };
  stubs_dir_in(out_dir, crate_name).join(file_name)
}

pub fn incremental_dir_of(package_dir: &Path) -> PathBuf {
  package_dir
      .join("target")
      .join("debug")
      .join("incremental")
}

pub fn src_dir_of(package_dir: &Path) -> PathBuf {
  package_dir.join("src")
}

pub fn valen_build_dir_of(valen_project_dir: &Path) -> PathBuf {
  valen_project_dir
      .join("target")
      .join("valen-build")
}

pub fn copy_dir_recursive(from: &Path, to: &Path) -> io::Result<()> {
  fs::create_dir_all(to)?;
  for entry in fs::read_dir(from)? {
    let entry = entry?;
    let source = entry.path();
    let dest = to.join(entry.file_name());
    if entry.file_type()?.is_dir() {
      copy_dir_recursive(&source, &dest)?;
    } else {
      fs::copy(&source, &dest)?;
    }
  }
  Ok(())
}
