use crate::typing::rust_interop::deps_dir_of;
use crate::typing::rust_interop::stubs_dir_of;
use std::fs::{copy, create_dir_all, read_dir, write};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;
use bumpalo::Bump;
use tempfile::TempDir;
use crate::{collect_only_tnode, collect_where_tnode, Keywords};
use crate::interner::StrI;
use crate::typing::ast::expressions::FunctionCallTE;
use crate::utils::code_hierarchy::PackageCoordinate;
use crate::compile_options::GlobalOptions;
use crate::instantiating::instantiating_interner::InstantiatingInterner;
use crate::instantiating::instantiator;
use crate::parse_arena::ParseArena;
use crate::postparsing::ScoutCompilation;
// use crate::typing::test::bifrost::spies::CaseOutcome;
use crate::scout_arena::ScoutArena;
// use crate::typing::test::bifrost::spies::Callee;
// use crate::typing::test::bifrost::spies::describe_callee;
// use crate::typing::test::bifrost::spies::CompileFailure;
use crate::typing::ast::ast::PrototypeT;
use crate::typing::compiler_outputs::CompilerOutputs;
use crate::typing::hinputs_t::HinputsT;
use crate::typing::names::names::{FunctionNameT, FunctionTemplateNameT, INameT, IdT};
use crate::typing::templata::templata::ITemplataT;
use crate::typing::test::traverse::NodeRefT;
// use crate::typing::test::bifrost::spies::InstantiationSummary;
use crate::typing::types::types::KindT;
use crate::typing::typing_interner::TypingInterner;
use crate::typing::{TypingPassCompilation, TypingPassOptions};
use crate::typing::oracles::Oracles;
use crate::utils::code_hierarchy::FileCoordinateMap;
use rustc_driver::{Callbacks, Compilation};
use rustc_interface::interface::Compiler as RustcCompiler;
use rustc_middle::ty::{Ty, TyCtxt, TyKind};
use crate::typing::test::bifrost::cargo_mimic::mimic_compile_dependency_rust_lib;

fn copy_dir_recursive(from: &Path, to: &Path) {
  create_dir_all(to).expect("could not create the destination directory");
  for entry in read_dir(from).expect("could not read the source directory") {
    let entry = entry.expect("could not read a directory entry");
    let source = entry.path();
    let dest = to.join(entry.file_name());
    if entry.file_type().expect("could not read the file type").is_dir() {
      copy_dir_recursive(&source, &dest);
    } else {
      copy(&source, &dest).expect("could not copy a file");
    }
  }
}

// Creates the -->'d paths in the below dir structure that our tests use:
//   <temp>/
//     testvalenproj/
//       src/bin.rs                          (not actually generated by tests, but here in spirit)
//       target/
//         debug/
// -->       deps/
//             valenc-stubs/
// -->           testvalenproj/
//                 bin.rs                    (input for the instantiating pass)
//             libsimple_dep_rust_lib.rlib   (rustc-compiled rlib from simple_dep_rust_lib)
//     simple_dep_rust_lib/                  (dir for a rust crate, copied from fixtures)
//       src/lib.rs
pub fn setup_test_temp_dir(valen_project_dir: &Path) {
  create_dir_all(&deps_dir_of(valen_project_dir)).expect("could not create the target/deps folder");
  create_dir_all(&stubs_dir_of(valen_project_dir)).expect("could not create the valenc-stubs folder");
}

// Creates the -->'d paths in the below dir structure that our tests use:
//   <temp>/
//     testvalenproj/
//       src/bin.rs                          (not actually generated by tests, but here in spirit)
//       target/
//         debug/
//           deps/
//             valenc-stubs/
//               testvalenproj/
//                 bin.rs                    (input for the instantiating pass)
//             libsimple_dep_rust_lib.rlib   (rustc-compiled rlib from simple_dep_rust_lib)
// --> simple_dep_rust_lib/                  (dir for a rust crate, copied from fixtures)
// -->   src/lib.rs
pub fn add_dependency_rust_lib(
  temp_dir: &Path,
  // This must be in the fixtures/ dir, we'll copy out of there.
  dependency_rust_lib_crate_name: &str
) {
  let fixture_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/typing/test/bifrost/fixtures");
  let source_fixture_dir_to_copy = fixture_dir.join(dependency_rust_lib_crate_name);
  let dep_crate_dir = temp_dir.join(dependency_rust_lib_crate_name);
  copy_dir_recursive(&source_fixture_dir_to_copy, &dep_crate_dir);
}
